/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWorkersIndexRouteImport } from './routes/_authenticated/workers.index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedBlacklistIndexRouteImport } from './routes/_authenticated/blacklist.index'
import { Route as AuthenticatedAdvancesIndexRouteImport } from './routes/_authenticated/advances.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedWorkersNewRouteImport } from './routes/_authenticated/workers.new'
import { Route as AuthenticatedWorkersIdRouteImport } from './routes/_authenticated/workers.$id'
import { Route as AuthenticatedBlacklistNewRouteImport } from './routes/_authenticated/blacklist.new'
import { Route as AuthenticatedAdvancesNewRouteImport } from './routes/_authenticated/advances.new'
import { Route as AuthenticatedAdvancesIdRouteImport } from './routes/_authenticated/advances.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTradesRouteImport } from './routes/_authenticated/admin.trades'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin.templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminDesignationsRouteImport } from './routes/_authenticated/admin.designations'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkersIndexRoute =
  AuthenticatedWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlacklistIndexRoute =
  AuthenticatedBlacklistIndexRouteImport.update({
    id: '/blacklist/',
    path: '/blacklist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvancesIndexRoute =
  AuthenticatedAdvancesIndexRouteImport.update({
    id: '/advances/',
    path: '/advances/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedWorkersNewRoute = AuthenticatedWorkersNewRouteImport.update({
  id: '/workers/new',
  path: '/workers/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkersIdRoute = AuthenticatedWorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlacklistNewRoute =
  AuthenticatedBlacklistNewRouteImport.update({
    id: '/blacklist/new',
    path: '/blacklist/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvancesNewRoute =
  AuthenticatedAdvancesNewRouteImport.update({
    id: '/advances/new',
    path: '/advances/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvancesIdRoute = AuthenticatedAdvancesIdRouteImport.update({
  id: '/advances/$id',
  path: '/advances/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTradesRoute =
  AuthenticatedAdminTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDesignationsRoute =
  AuthenticatedAdminDesignationsRouteImport.update({
    id: '/designations',
    path: '/designations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/designations': typeof AuthenticatedAdminDesignationsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/advances/$id': typeof AuthenticatedAdvancesIdRoute
  '/advances/new': typeof AuthenticatedAdvancesNewRoute
  '/blacklist/new': typeof AuthenticatedBlacklistNewRoute
  '/workers/$id': typeof AuthenticatedWorkersIdRoute
  '/workers/new': typeof AuthenticatedWorkersNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/advances/': typeof AuthenticatedAdvancesIndexRoute
  '/blacklist/': typeof AuthenticatedBlacklistIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/workers/': typeof AuthenticatedWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/designations': typeof AuthenticatedAdminDesignationsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/advances/$id': typeof AuthenticatedAdvancesIdRoute
  '/advances/new': typeof AuthenticatedAdvancesNewRoute
  '/blacklist/new': typeof AuthenticatedBlacklistNewRoute
  '/workers/$id': typeof AuthenticatedWorkersIdRoute
  '/workers/new': typeof AuthenticatedWorkersNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/advances': typeof AuthenticatedAdvancesIndexRoute
  '/blacklist': typeof AuthenticatedBlacklistIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/workers': typeof AuthenticatedWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/designations': typeof AuthenticatedAdminDesignationsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/advances/$id': typeof AuthenticatedAdvancesIdRoute
  '/_authenticated/advances/new': typeof AuthenticatedAdvancesNewRoute
  '/_authenticated/blacklist/new': typeof AuthenticatedBlacklistNewRoute
  '/_authenticated/workers/$id': typeof AuthenticatedWorkersIdRoute
  '/_authenticated/workers/new': typeof AuthenticatedWorkersNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/advances/': typeof AuthenticatedAdvancesIndexRoute
  '/_authenticated/blacklist/': typeof AuthenticatedBlacklistIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/workers/': typeof AuthenticatedWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/admin/audit'
    | '/admin/designations'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/trades'
    | '/admin/users'
    | '/advances/$id'
    | '/advances/new'
    | '/blacklist/new'
    | '/workers/$id'
    | '/workers/new'
    | '/admin/'
    | '/advances/'
    | '/blacklist/'
    | '/documents/'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/admin/audit'
    | '/admin/designations'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/trades'
    | '/admin/users'
    | '/advances/$id'
    | '/advances/new'
    | '/blacklist/new'
    | '/workers/$id'
    | '/workers/new'
    | '/admin'
    | '/advances'
    | '/blacklist'
    | '/documents'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/designations'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/trades'
    | '/_authenticated/admin/users'
    | '/_authenticated/advances/$id'
    | '/_authenticated/advances/new'
    | '/_authenticated/blacklist/new'
    | '/_authenticated/workers/$id'
    | '/_authenticated/workers/new'
    | '/_authenticated/admin/'
    | '/_authenticated/advances/'
    | '/_authenticated/blacklist/'
    | '/_authenticated/documents/'
    | '/_authenticated/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/': {
      id: '/_authenticated/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AuthenticatedWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blacklist/': {
      id: '/_authenticated/blacklist/'
      path: '/blacklist'
      fullPath: '/blacklist/'
      preLoaderRoute: typeof AuthenticatedBlacklistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advances/': {
      id: '/_authenticated/advances/'
      path: '/advances'
      fullPath: '/advances/'
      preLoaderRoute: typeof AuthenticatedAdvancesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/workers/new': {
      id: '/_authenticated/workers/new'
      path: '/workers/new'
      fullPath: '/workers/new'
      preLoaderRoute: typeof AuthenticatedWorkersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/$id': {
      id: '/_authenticated/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof AuthenticatedWorkersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blacklist/new': {
      id: '/_authenticated/blacklist/new'
      path: '/blacklist/new'
      fullPath: '/blacklist/new'
      preLoaderRoute: typeof AuthenticatedBlacklistNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advances/new': {
      id: '/_authenticated/advances/new'
      path: '/advances/new'
      fullPath: '/advances/new'
      preLoaderRoute: typeof AuthenticatedAdvancesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advances/$id': {
      id: '/_authenticated/advances/$id'
      path: '/advances/$id'
      fullPath: '/advances/$id'
      preLoaderRoute: typeof AuthenticatedAdvancesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trades': {
      id: '/_authenticated/admin/trades'
      path: '/trades'
      fullPath: '/admin/trades'
      preLoaderRoute: typeof AuthenticatedAdminTradesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/designations': {
      id: '/_authenticated/admin/designations'
      path: '/designations'
      fullPath: '/admin/designations'
      preLoaderRoute: typeof AuthenticatedAdminDesignationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDesignationsRoute: typeof AuthenticatedAdminDesignationsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminTradesRoute: typeof AuthenticatedAdminTradesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDesignationsRoute: AuthenticatedAdminDesignationsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminTradesRoute: AuthenticatedAdminTradesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdvancesIdRoute: typeof AuthenticatedAdvancesIdRoute
  AuthenticatedAdvancesNewRoute: typeof AuthenticatedAdvancesNewRoute
  AuthenticatedBlacklistNewRoute: typeof AuthenticatedBlacklistNewRoute
  AuthenticatedWorkersIdRoute: typeof AuthenticatedWorkersIdRoute
  AuthenticatedWorkersNewRoute: typeof AuthenticatedWorkersNewRoute
  AuthenticatedAdvancesIndexRoute: typeof AuthenticatedAdvancesIndexRoute
  AuthenticatedBlacklistIndexRoute: typeof AuthenticatedBlacklistIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedWorkersIndexRoute: typeof AuthenticatedWorkersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdvancesIdRoute: AuthenticatedAdvancesIdRoute,
  AuthenticatedAdvancesNewRoute: AuthenticatedAdvancesNewRoute,
  AuthenticatedBlacklistNewRoute: AuthenticatedBlacklistNewRoute,
  AuthenticatedWorkersIdRoute: AuthenticatedWorkersIdRoute,
  AuthenticatedWorkersNewRoute: AuthenticatedWorkersNewRoute,
  AuthenticatedAdvancesIndexRoute: AuthenticatedAdvancesIndexRoute,
  AuthenticatedBlacklistIndexRoute: AuthenticatedBlacklistIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedWorkersIndexRoute: AuthenticatedWorkersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
